# 读取文件
with open('web/templates/phase-one-setup-new.html', 'r', encoding='utf-8') as f:
    content = f.read()

# 14. 替换高潮阶段
content = content.replace(
    '<div style="position: relative; margin-bottom: 40px; padding-left: 80px; width: 100%; max-width: 100%; box-sizing: border-box;" data-stage="climax">\n                                <!-- 时间线节点 -->\n                                <div style="position: absolute; left: 16px; top: 24px; width: 32px; height: 32px; background: linear-gradient(135deg, #fee2e2 0%, #fecaca 100%); border: 3px solid #ef4444; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 16px; z-index: 2; box-shadow: 0 0 0 4px rgba(239, 68, 68, 0.1);">🔥</div>\n                                \n                                <!-- 阶段内容 -->\n                                <div style="background: linear-gradient(135deg, #fef2f2 0%, #fee2e2 100%); border: 2px solid #ef4444; border-radius: 12px; padding: 20px; box-shadow: 0 4px 12px rgba(239, 68, 68, 0.15); width: 100%; max-width: 100%; box-sizing: border-box; overflow: hidden;">\n                                    <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 16px;">\n                                        <div style="width: 24px; height: 24px; background: #ef4444; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 12px; color: white; font-weight: bold;">3</div>\n                                        <h5 style="color: #991b1b; margin: 0; font-size: 18px; font-weight: 700;">高潮阶段</h5>\n                                    </div>\n                                    <input type="text" class="stage-name" data-stage="climax" placeholder="高潮阶段名称（如：终极对决）" value="" style="width: 100%; max-width: 100%; margin-bottom: 12px; padding: 14px 16px; border: 2px solid #ef4444; border-radius: 8px; font-size: 15px; background: white; color: #1f2937; font-weight: 600; box-sizing: border-box; display: block;">\n                                    <textarea class="stage-description" data-stage="climax" rows="5" placeholder="描述故事的高潮冲突：\n\n• 主要矛盾的集中爆发\n• 关键转折点和重要选择\n• 主角实力的巅峰展现\n• 反派势力的最终对决\n• 故事主题的深刻体现" style="width: 100%; max-width: 100%; padding: 16px; border: 2px solid #ef4444; border-radius: 8px; font-size: 14px; background: white; color: #1f2937; resize: vertical; min-height: 120px; line-height: 1.6; box-sizing: border-box; display: block;"></textarea>\n                                </div>\n                            </div>',
    '<div class="stage-editor stage-climax" data-stage="climax">\n                                <div class="stage-node">🔥</div>\n                                <div class="stage-content">\n                                    <div class="stage-header">\n                                        <div class="stage-number">3</div>\n                                        <h5 class="stage-title">高潮阶段</h5>\n                                    </div>\n                                    <input type="text" class="stage-name editor-input" data-stage="climax" placeholder="高潮阶段名称（如：终极对决）" value="">\n                                    <textarea class="stage-description editor-textarea" data-stage="climax" rows="5" placeholder="描述故事的高潮冲突：\n\n• 主要矛盾的集中爆发\n• 关键转折点和重要选择\n• 主角实力的巅峰展现\n• 反派势力的最终对决\n• 故事主题的深刻体现"></textarea>\n                                </div>\n                            </div>'
)

# 15. 替换结局阶段
content = content.replace(
    '<div style="position: relative; padding-left: 80px; width: 100%; max-width: 100%; box-sizing: border-box;" data-stage="ending">\n                                <!-- 时间线节点 -->\n                                <div style="position: absolute; left: 16px; top: 24px; width: 32px; height: 32px; background: linear-gradient(135deg, #d1fae5 0%, #a7f3d0 100%); border: 3px solid #10b981; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 16px; z-index: 2; box-shadow: 0 0 0 4px rgba(16, 185, 129, 0.1);">🎯</div>\n                                \n                                <!-- 阶段内容 -->\n                                <div style="background: linear-gradient(135deg, #ecfdf5 0%, #d1fae5 100%); border: 2px solid #10b981; border-radius: 12px; padding: 20px; box-shadow: 0 4px 12px rgba(16, 185, 129, 0.15); width: 100%; max-width: 100%; box-sizing: border-box; overflow: hidden;">\n                                    <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 16px;">\n                                        <div style="width: 24px; height: 24px; background: #10b981; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 12px; color: white; font-weight: bold;">4</div>\n                                        <h5 style="color: #064e3b; margin: 0; font-size: 18px; font-weight: 700;">结局阶段</h5>\n                                    </div>\n                                    <input type="text" class="stage-name" data-stage="ending" placeholder="结局阶段名称（如：功成身退）" value="" style="width: 100%; max-width: 100%; margin-bottom: 12px; padding: 14px 16px; border: 2px solid #10b981; border-radius: 8px; font-size: 15px; background: white; color: #1f2937; font-weight: 600; box-sizing: border-box; display: block;">\n                                    <textarea class="stage-description" data-stage="ending" rows="5" placeholder="描述故事的结局：\n\n• 主要冲突的最终解决\n• 人物命运和关系的归宿\n• 主题思想的升华和总结\n• 对未来的展望或新的开始\n• 给读者的思考和感悟" style="width: 100%; max-width: 100%; padding: 16px; border: 2px solid #10b981; border-radius: 8px; font-size: 14px; background: white; color: #1f2937; resize: vertical; min-height: 120px; line-height: 1.6; box-sizing: border-box; display: block;"></textarea>\n                                </div>\n                            </div>',
    '<div class="stage-editor stage-ending" data-stage="ending">\n                                <div class="stage-node">🎯</div>\n                                <div class="stage-content">\n                                    <div class="stage-header">\n                                        <div class="stage-number">4</div>\n                                        <h5 class="stage-title">结局阶段</h5>\n                                    </div>\n                                    <input type="text" class="stage-name editor-input" data-stage="ending" placeholder="结局阶段名称（如：功成身退）" value="">\n                                    <textarea class="stage-description editor-textarea" data-stage="ending" rows="5" placeholder="描述故事的结局：\n\n• 主要冲突的最终解决\n• 人物命运和关系的归宿\n• 主题思想的升华和总结\n• 对未来的展望或新的开始\n• 给读者的思考和感悟"></textarea>\n                                </div>\n                            </div>'
)

# 16. 替换生成设置区块
content = content.replace(
    '<div style="margin-bottom: 16px; background: white; border-radius: 12px; padding: 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); border: 1px solid #e5e7eb;">\n                        <div style="display: flex; align-items: center; gap: 12px; margin-bottom: 20px;">\n                            <div style="width: 32px; height: 32px; background: linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%); border-radius: 8px; display: flex; align-items: center; justify-content: center; font-size: 16px; color: white;">🎛️</div>\n                            <h4 style="color: #1f2937; margin: 0; font-size: 18px; font-weight: 700;">生成设置</h4>\n                        </div>\n                        <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px;">\n                            <div>\n                                <label for="edit-total-chapters" style="display: block; margin-bottom: 8px; font-weight: 600; color: #374151; font-size: 14px;">总章节数</label>\n                                <input type="number" id="edit-total-chapters" name="total_chapters" value="200" min="1" max="200" style="width: 100%; padding: 14px 16px; border: 2px solid #e5e7eb; border-radius: 10px; font-size: 15px; background: white; color: #1f2937; font-weight: 500; box-sizing: border-box;">\n                            </div>\n                        </div>\n                    </div>',
    '<div class="editor-section">\n                        <div class="editor-section-header">\n                            <div class="editor-section-icon info">🎛️</div>\n                            <h4 class="editor-section-title">生成设置</h4>\n                        </div>\n                        <div class="editor-form-row">\n                            <div class="editor-form-group">\n                                <label for="edit-total-chapters" class="editor-label">总章节数</label>\n                                <input type="number" id="edit-total-chapters" class="editor-input" name="total_chapters" value="200" min="1" max="200">\n                            </div>\n                        </div>\n                    </div>'
)

# 保存文件
with open('web/templates/phase-one-setup-new.html', 'w', encoding='utf-8') as f:
    f.write(content)

print('第四部分替换完成')
