# 读取文件
with open('web/templates/phase-one-setup-new.html', 'r', encoding='utf-8') as f:
    content = f.read()

# 11. 替换时间轴容器
content = content.replace(
    '<div style="position: relative; padding: 20px 0; width: 100%; max-width: 100%; margin: 0 auto; box-sizing: border-box;">\n                            <!-- 时间线主线 -->\n                            <div style="position: absolute; left: 30px; top: 40px; bottom: 40px; width: 4px; background: linear-gradient(180deg, #fbbf24 0%, #3b82f6 50%, #ef4444 75%, #10b981 100%); border-radius: 2px;"></div>',
    '<div class="storyline-container">\n                            <div class="storyline-timeline"></div>'
)

# 12. 替换开篇阶段
content = content.replace(
    '<div style="position: relative; margin-bottom: 40px; padding-left: 80px; width: 100%; max-width: 100%; box-sizing: border-box;" data-stage="opening">\n                                <!-- 时间线节点 -->\n                                <div style="position: absolute; left: 16px; top: 24px; width: 32px; height: 32px; background: linear-gradient(135deg, #fef3c7 0%, #fde68a 100%); border: 3px solid #fbbf24; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 16px; z-index: 2; box-shadow: 0 0 0 4px rgba(251, 191, 36, 0.1);">🎬</div>\n                                \n                                <!-- 阶段内容 -->\n                                <div style="background: linear-gradient(135deg, #fef9e7 0%, #fef3c7 100%); border: 2px solid #fbbf24; border-radius: 12px; padding: 20px; box-shadow: 0 4px 12px rgba(251, 191, 36, 0.15); width: 100%; max-width: 100%; box-sizing: border-box; overflow: hidden;">\n                                    <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 16px;">\n                                        <div style="width: 24px; height: 24px; background: #fbbf24; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 12px; color: white; font-weight: bold;">1</div>\n                                        <h5 style="color: #92400e; margin: 0; font-size: 18px; font-weight: 700;">开篇阶段</h5>\n                                    </div>\n                                    <input type="text" class="stage-name" data-stage="opening" placeholder="开篇阶段名称（如：初入仙门）" value="" style="width: 100%; max-width: 100%; margin-bottom: 12px; padding: 14px 16px; border: 2px solid #f59e0b; border-radius: 8px; font-size: 15px; background: white; color: #1f2937; font-weight: 600; box-sizing: border-box; display: block;">\n                                    <textarea class="stage-description" data-stage="opening" rows="5" placeholder="描述故事的开端：\n\n• 主角出场背景和初始状态\n• 核心冲突或目标的引入\n• 重要配角的初次登场\n• 世界观和基本设定的展现\n• 为后续发展埋下伏笔" style="width: 100%; max-width: 100%; padding: 16px; border: 2px solid #f59e0b; border-radius: 8px; font-size: 14px; background: white; color: #1f2937; resize: vertical; min-height: 120px; line-height: 1.6; box-sizing: border-box; display: block;"></textarea>\n                                </div>\n                            </div>',
    '<div class="stage-editor stage-opening" data-stage="opening">\n                                <div class="stage-node">🎬</div>\n                                <div class="stage-content">\n                                    <div class="stage-header">\n                                        <div class="stage-number">1</div>\n                                        <h5 class="stage-title">开篇阶段</h5>\n                                    </div>\n                                    <input type="text" class="stage-name editor-input" data-stage="opening" placeholder="开篇阶段名称（如：初入仙门）" value="">\n                                    <textarea class="stage-description editor-textarea" data-stage="opening" rows="5" placeholder="描述故事的开端：\n\n• 主角出场背景和初始状态\n• 核心冲突或目标的引入\n• 重要配角的初次登场\n• 世界观和基本设定的展现\n• 为后续发展埋下伏笔"></textarea>\n                                </div>\n                            </div>'
)

# 13. 替换发展阶段
content = content.replace(
    '<div style="position: relative; margin-bottom: 40px; padding-left: 80px; width: 100%; max-width: 100%; box-sizing: border-box;" data-stage="development">\n                                <!-- 时间线节点 -->\n                                <div style="position: absolute; left: 16px; top: 24px; width: 32px; height: 32px; background: linear-gradient(135deg, #dbeafe 0%, #bfdbfe 100%); border: 3px solid #3b82f6; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 16px; z-index: 2; box-shadow: 0 0 0 4px rgba(59, 130, 246, 0.1);">📈</div>\n                                \n                                <!-- 阶段内容 -->\n                                <div style="background: linear-gradient(135deg, #eff6ff 0%, #dbeafe 100%); border: 2px solid #3b82f6; border-radius: 12px; padding: 20px; box-shadow: 0 4px 12px rgba(59, 130, 246, 0.15); width: 100%; max-width: 100%; box-sizing: border-box; overflow: hidden;">\n                                    <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 16px;">\n                                        <div style="width: 24px; height: 24px; background: #3b82f6; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 12px; color: white; font-weight: bold;">2</div>\n                                        <h5 style="color: #1e3a8a; margin: 0; font-size: 18px; font-weight: 700;">发展阶段</h5>\n                                    </div>\n                                    <input type="text" class="stage-name" data-stage="development" placeholder="发展阶段名称（如：历练成长）" value="" style="width: 100%; max-width: 100%; margin-bottom: 12px; padding: 14px 16px; border: 2px solid #3b82f6; border-radius: 8px; font-size: 15px; background: white; color: #1f2937; font-weight: 600; box-sizing: border-box; display: block;">\n                                    <textarea class="stage-description" data-stage="development" rows="5" placeholder="描述故事的成长发展：\n\n• 主角能力的提升和成长\n• 新角色和势力的引入\n• 副线情节的展开\n• 世界观的进一步拓展\n• 为高潮阶段做铺垫" style="width: 100%; max-width: 100%; padding: 16px; border: 2px solid #3b82f6; border-radius: 8px; font-size: 14px; background: white; color: #1f2937; resize: vertical; min-height: 120px; line-height: 1.6; box-sizing: border-box; display: block;"></textarea>\n                                </div>\n                            </div>',
    '<div class="stage-editor stage-development" data-stage="development">\n                                <div class="stage-node">📈</div>\n                                <div class="stage-content">\n                                    <div class="stage-header">\n                                        <div class="stage-number">2</div>\n                                        <h5 class="stage-title">发展阶段</h5>\n                                    </div>\n                                    <input type="text" class="stage-name editor-input" data-stage="development" placeholder="发展阶段名称（如：历练成长）" value="">\n                                    <textarea class="stage-description editor-textarea" data-stage="development" rows="5" placeholder="描述故事的成长发展：\n\n• 主角能力的提升和成长\n• 新角色和势力的引入\n• 副线情节的展开\n• 世界观的进一步拓展\n• 为高潮阶段做铺垫"></textarea>\n                                </div>\n                            </div>'
)

# 保存文件
with open('web/templates/phase-one-setup-new.html', 'w', encoding='utf-8') as f:
    f.write(content)

print('第三部分替换完成')
