# -*- mode: python ; coding: utf-8 -*-
# 单文件版本 (onefile) - 体积更小，约 70MB

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'PyQt5.QtWidgets',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'playwright',
        'playwright.sync_api',
        'playwright._impl',
        'playwright._impl._driver',
        'playwright._impl._connection',
        'greenlet',
        'pyee',
        'pyee.base',
        'websockets',
        'websockets.client',
        'fanqie_uploader_impl',
        'tomato_account_manager',
        'chrome_manager',
        'token_manager',
        'api_auth',
        'config_env',
        'styles',
        'version',
    ],
    hookspath=['.'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'tkinter',
        'unittest',
        'pytest',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    # onefile 关键设置：不要 exclude_binaries，不要 COLLECT
    [],
    name='NovelPublisher',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='app_icon.ico',
)
