# -*- mode: python ; coding: utf-8 -*-
# 优化版本 - 约 70MB

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],  # 不打包 libs 目录，依赖系统 Python 环境
    hiddenimports=[
        'PyQt5.QtWidgets',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'playwright',
        'playwright.sync_api',
        'playwright._impl',
        'playwright._impl._driver',
        'playwright._impl._connection',
        'greenlet',
        'pyee',
        'pyee.base',
        'websockets',
        'websockets.client',
        'fanqie_uploader_impl',
        'tomato_account_manager',
        'chrome_manager',
        'token_manager',
        'api_auth',
        'config_env',
        'styles',
        'version',
    ],
    hookspath=['.'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # PyQt5 不需要的模块
        'PyQt5.QtBluetooth',
        'PyQt5.QtDBus',
        'PyQt5.QtDesigner',
        'PyQt5.QtHelp',
        'PyQt5.QtLocation',
        'PyQt5.QtMultimedia',
        'PyQt5.QtMultimediaWidgets',
        'PyQt5.QtNetwork',
        'PyQt5.QtNfc',
        'PyQt5.QtOpenGL',
        'PyQt5.QtPositioning',
        'PyQt5.QtPrintSupport',
        'PyQt5.QtQml',
        'PyQt5.QtQuick',
        'PyQt5.QtQuick3D',
        'PyQt5.QtQuickWidgets',
        'PyQt5.QtRemoteObjects',
        'PyQt5.QtSensors',
        'PyQt5.QtSerialPort',
        'PyQt5.QtSql',
        'PyQt5.QtSvg',
        'PyQt5.QtTest',
        'PyQt5.QtTextToSpeech',
        'PyQt5.QtWebChannel',
        'PyQt5.QtWebSockets',
        'PyQt5.QtWinExtras',
        'PyQt5.QtXml',
        'PyQt5.QtXmlPatterns',
        # 其他不需要的模块
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'PIL',
        'sklearn',
        'tensorflow',
        'torch',
        'cv2',
        'boto3',
        'botocore',
        'tkinter',
        'unittest',
        'pytest',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='NovelPublisher',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='app_icon.ico',
)
